[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# For openzeppelin-foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# End of for openzeppelin-foundry-upgrades
